### ISSUE TITLE
Enhancement: PR template

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM#120]
**Summary**
Much like ISSUE_TEMPLATE, we should have PR templates to include common steps, e.g., version bump, Linked issues/PRs.

**Objectives**
1. Have one generic one for features
2. Have one for hotfixes and releases

**Proposal**

*Testing notes*

*Additional notes*

**Implemented in**: TBD

**Comment by astrochun** [comment]
Some examples:

https://github.com/flexyford/pull-request-template
https://github.com/stevemao/github-issue-templates/blob/master/must-open-issue-before-pr/PULL_REQUEST_TEMPLATE.md

**Comment by damian-romero** [comment]
I think it would be good to be specific about the PR labels, so have one template for each type:
- Features
- Bugs
- Releases
