### ISSUE TITLE
Chore: Add docs checkmark to PR templates

### ISSUE THREAD

**Issue by damian-romero** [UAL-RE/ReQUIAM#135]
After documentation with RTDs #66 is finished, add checkmark reminders to update documentation on:

- bug-pull-request.md
- release-pull-request.md

Implement as hotfix

**Comment by damian-romero** [comment]
Unassigning myself.

**Comment by zoidy** [comment]
bug fix and feature templates should be updated once #173 is merged.

**Comment by zoidy** [comment]
Reopening. I only had time to update the release template which is why I didn't close it.
