### ISSUE TITLE
Dry run when updating quotas resulted in error

### ISSUE THREAD

**Issue by zoidy** [UAL-RE/ReQUIAM#54]
Did a dry run which updated portals and quotas. Portals ran without errors but quotas failed. These are the last few lines of the log

21:58:36 -     INFO: Working on grad quota : 536870912 bytes
22:00:38 -     INFO: Removing : ['figshare01-test', 'kalcock']
22:00:38 -     INFO:  EDS size 16082
Traceback (most recent call last):
  File "scripts/script_run", line 238, in <module>
    grouper_group=grouper_quota)
  File "/home/mozart/codes/ReQUIAM/requiam/grouper_query.py", line 42, in __init__
    if 'wsSubjects' in rsp.json()['WsGetMembersLiteResult']:
  File "/opt/anaconda3/envs/figshare_patrons/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/anaconda3/envs/figshare_patrons/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/envs/figshare_patrons/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/envs/figshare_patrons/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I also have a question about why 'figshare01-test', 'kalcock' and  sometimes 'chunly' were going to be removed from every group. Presumably they should only be removed from groups they're actually in? It could be a symptom of me not fully understanding the log output. I can make a separate issue for this if needed

**Comment by astrochun** [comment]
First this is particularly weird.  It worked fine on the 100MB set and then died on the 500MB.  Specifically, it died on the attempt to retrieve the Grouper member list for `536870912`.  This might be an issue with Grouper and not us.  I'll have to dig deeper.

Note: There's still effort need to updated our manual files for the test accounts, so performing sync is not recommended.  This will change many things that I have put in place for other testing.

Regarding the extra list of members, yes I'm aware of this.  It has to do with simple logical statements and how these operations work.  Set logic will not remove users if those users are not in the list.  The messaging needs to be revised but that's not just a few line fix.  I'm trying to find a simple solution that doesn't increase compute time.

**Comment by astrochun** [comment]
A re-run of the `script_run` yielded no failures (Exit 0 returned as expected), especially where the error occurred.  I suspect that there was an issue with Grouper itself and not ReQUIAM script.

The issue involving additional user names (associated with `manual_override`) is connected with #39 (verbose) logging, so I'll update that issue and close this issue out.
