### ISSUE TITLE
PEP8 compliance and documentation

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM#6]
General issue for best practices.  This ticket will remain open indefinitely.

**Comment by astrochun** [comment]
README.md has been a bit outdated. It needs to include discussion of

- [x] Provide description on configuration settings [6194252]
- [ ] Documentation of manual override [338c08f]

**Comment by damian-romero** [comment]
While working on #93 I found some style issues including:
1. multiple spaces before assignments in several scripts as in `scripts/org_code_numbers.py`
```
a    = 'a'
ab   = 'ab'
abc  = 'abc'
```
2. F-strings with no place holders as in `f'foo bar'` in `scripts/manual_override.py`
3.  Some unused imports like `from os import path` and `from os import mkdir` in `scripts/org_code_numbers.py`

I am not sure if `1` is for clarity, but I think fixing the other ones could be part of this issue.
