### ISSUE TITLE
Script to check Grouper-EDS sync

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM#71]
The script could simply be executed after the main script `script_run` to show summary data.

This would help to identify any sync issue.

This would be beneficial to also have it when `user_update` script is executed.  There may be a few minute delayed needed.

**Comment by yhan818** [comment]
"SUMMARY" is logged at the end of the script_run. I do not see any reason to have this script needed. Maybe this issue shall be just closed.
