### ISSUE TITLE
Change all python scripts to executable

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM#82]
The following scripts should be made executable (`chmod +x`):
1. `add_grouper_groups`
2. `get_org_code_numbers`
3. ~`grouper_permission_checks`~ (not part of v0.13.4)
4. `script_run`
5. `user_update`

This can be implemented as `hotfix/v0.13.5`

Also, updates to [README.md](README.md) for simpler execution.

Although outside this issue, for deployment aliases on patron server needs to be modified. This is not crucial but helps to keep things clean.

**Comment by damian-romero** [comment]
I don't see `grouper_permission_checks` in this version on Master.

**Comment by astrochun** [comment]
> I don't see `grouper_permission_checks` in this version on Master.

Ah yes, it is a code that I had not pushed.  I'll do that at some point and will ensure it's executable.  For now focus on the rest of the scripts for this hotfix.
